routes/web.php
<?php

use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoomController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('room', RoomController::class);
Route::resource('movie', MovieController::class);

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    use HasFactory;
    // show room from Room
    public function room()
    {
        return $this->hasMany(Room::class);
    }
    // protected fillable from movie table
    protected $fillable = [
        'title',
        'genre',
        'des',
        'poster',
        'director',
    ];
}

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;
    public function movies()
    {
        return $this->belongsTo(Movie::class, 'movie');
    }
    protected $fillable = [
        'no_room',
        'no_chairs',
        'movie',
    ];


}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Models\Movie;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::all();
        return view('movies.index', compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('movies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $movie = new Movie();
        $file = $request->file('poster');
        $ext = $file->extension();
        $filename = time() . '.' . $ext;
        $movie->poster = "posters/" . $filename;
        $movie->title = $request->title;
        $movie->director = $request->director;
        $movie->genre = $request->genre;
        $movie->des = $request->des;

        $file->move("posters/", $filename);
        $movie->save();
        return redirect('movie');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $movie = Movie::find($id);
        return view('movies.show', compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $movie = Movie::find($id);
        return view('movies.edit', compact('movie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $movie = Movie::find($id);
        $movie->title = $request->title;
        $movie->director = $request->director;
        $movie->genre = $request->genre;
        $file = $request->file('poster');
        if (!empty($file)) {

            $ext = $file->extension();
            $filename = time() . '.' . $ext;
            $movie->poster = "posters/" . $filename;
            $file->move("posters/", $filename);
        }

        $movie->des = $request->des;
        $movie->update();
        return redirect('movie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $movie = Movie::find($id);
        $movie->delete();
        return redirect('movie');
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\Movie;
use App\Models\Room;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rooms = Room::all();
        return view('rooms.index', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // movie from Movie
        $movies = Movie::all();
        return view('rooms.create', compact('movies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $room = new Room();
        $room->no_room = $request->no_room;
        $room->no_chairs = $request->no_chairs;
        $room->movie = $request->movie;

        $room->save();

        return redirect('room');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $room = Room::find($id);
        return view('rooms.show', compact('room'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $room = Room::find($id);
        $movies = Movie::all();
        return view('rooms.edit', compact('room' , 'movies'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $room = Room::find($id);
        $room->no_room = $request->no_room;
        $room->no_chairs = $request->no_chairs;
        $room->movie = $request->movie;

        $room->save();

        return redirect('room');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $room = Room::find($id);
        $room->delete();

        return redirect('room');
    }
}

resources/views/home.blade.php
@extends('welcome')
@section('content')
    <div class="flex justify-center">
        <div class="card w-96 bg-base-100 shadow-xl " data-theme="light">
            <figure class="px-10 pt-10">
                <img src="https://en.parisinfo.com/var/otcp/sites/images/node_43/node_51/node_7112/salle-de-cin%C3%A9ma-%7C-630x405-%7C-%C2%A9-fotolia-he2/12344768-1-fre-FR/Salle-de-cin%C3%A9ma-%7C-630x405-%7C-%C2%A9-Fotolia-he2.jpg" alt="Shoes" class="rounded-xl" />
            </figure>
            <div class="card-body items-center text-center">
                <h2 class="card-title">This is a Cinema Management Website</h2>
                <p>In this website you can aquir informations about the room in which your desired film will be played,and what other films will be displayed in that very room.</p>

            </div>
        </div>
    </div>
@endsection

resources/views/movies/create.blade.php
@extends('welcome')
@section('content')

    <div class="flex justify-center mt-5">
        <div class="card w-96 bg-base-100 shadow-xl" data-theme="light">
            <div class="card-body items-center text-center">
                <form action="{{ route('movie.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="flex justify-center mb-5">
                        <a href="{{ route('movie.index') }}" class="btn btn-success">Go Back</a>
                    </div>
                    <label for="" class='text-lg '>Title</label>
                    <input type="text" placeholder="Type here"
                        class="input input-bordered input-primary w-full max-w-xs mt-3" name="title"/><br><br>
                    <label for="" class='text-lg'>Genre</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="genre"/><br><br>
                    <label for="" class='text-lg'>Director</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="director"/><br><br>
                    <label for="" class='text-lg'>Description</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="des"/><br><br>
                    <label for="" class='text-lg'>Poster</label>
                    <input type="file"
                        class="file-input file-input-bordered file-input-primary w-full max-w-xs" name="poster"/><br><br>
                    <div class="flex justify-center">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>


@endsection

resources/views/movies/edit.blade.php
@extends('welcome')
@section('content')

    <div class="flex justify-center mt-5">
        <div class="card w-96 bg-base-100 shadow-xl" data-theme="light">
            <div class="card-body items-center text-center">
                <form action="{{ route('movie.update',$movie->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="flex justify-center mb-5">
                        <a href="{{ route('movie.index') }}" class="btn btn-success">Go Back</a>
                    </div>
                    <label for="" class='text-lg '>Title</label>
                    <input type="text" placeholder="Type here"
                        class="input input-bordered input-primary w-full max-w-xs mt-3" name="title" value="{{ $movie->title }}"/><br><br>
                    <label for="" class='text-lg'>Genre</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="genre" value="{{ $movie->genre }}"/><br><br>
                    <label for="" class='text-lg'>Director</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="director" value="{{ $movie->director }}"/><br><br>
                    <label for="" class='text-lg'>Description</label>
                    <input type="text" placeholder="Type here"
                        class="mt-3 input input-bordered input-primary w-full max-w-xs" name="des" value="{{ $movie->des }}"/><br><br>
                    <label for="" class='text-lg'>Poster</label>
                    <input type="file"
                        class="file-input file-input-bordered file-input-primary w-full max-w-xs" name="poster"/><br><br>
                    <div class="flex justify-center">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>


@endsection

resources/views/movies/index.blade.php
@extends('welcome')
@section('content')
<div class="m-5 flex justify-end" >
    <a class="btn btn-success" href="{{ route('movie.create') }}">Add</a>
</div>
<div class="m-5" >
    <div class="overflow-x-auto" >
        <table class="table table-zebra w-full rounded-lg" data-theme="light">
          <!-- head -->
          <thead>
            <tr>
              <th>Title</th>
              <th>Genre</th>
              <th>Director</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($movies as $item)
                <tr>
                    <td>{{ $item->title }}</td>
                    <td>{{ $item->genre }}</td>
                    <td>{{ $item->director }}</td>
                    <td>
                        <form action="{{ route('movie.destroy',$item->id) }}" method="post">
                            @csrf
                            @method('DELETE')

                            <a href="{{ route('movie.show',$item->id) }}" class="btn btn-primary">Show</a>
                            <a href="{{ route('movie.edit',$item->id) }}" class="btn btn-warning">Edit</a>
                            <button class="btn btn-error" onClick="return confirm('Are you sure you want to do this?')">Delete</button>
                        </form>
                    </td>
                </tr>

            @endforeach
          </tbody>
        </table>
      </div>
</div>
@endsection

resources/views/movies/show.blade.php
@extends('welcome')
@section('content')
<div class="m-5 flex justify-center">
    <div class="card w-96 bg-base-100 shadow-xl" data-theme='light'>
        <figure class="m-5"><img src={{ asset($movie->poster) }} alt="Poster" class="rounded-xl"/></figure>
        <div class="card-body items-center text-center">
          <h2 class="card-title">
            {{ $movie->title }} By {{ $movie->director }}
          </h2>
          <p>{{ $movie->des }}</p>
          <div class="card-actions justify-end">
            <div class="badge badge-outline">{{ $movie->genre }}</div>
          </div>
        </div>
      </div>


</div>







@endsection

resources/views/rooms/create.blade.php
@extends('welcome')
@section('content')

    <div class="flex justify-center mt-5">
        <div class="card w-96 bg-base-100 shadow-xl" data-theme="light">
            <div class="card-body items-center text-center">
                <form action="{{ route('room.store') }}" method="post" >
                    @csrf
                    <div class="flex justify-center mb-5">
                        <a href="{{ route('room.index') }}" class="btn btn-success">Go Back</a>
                    </div>
                    {{-- form inputs(no_room,no_chairs)from room and input(movie) from movie --}}
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text">Room Number</span>
                        </label>
                        <input type="text" name="no_room" placeholder="Room Number" class="input input-bordered">
                    </div>
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text">Number of Chairs</span>
                        </label>
                        <input type="text" name="no_chairs" placeholder="Number of Chairs" class="input input-bordered">
                    </div>
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text">Movie</span>
                        </label>
                        <select name="movie" class="select select-bordered w-full max-w-xs">
                            <option value="">Select Movie</option>
                            @foreach ($movies as $movie)
                                <option value="{{ $movie->id }}">{{ $movie->title }}</option>
                            @endforeach
                        </select>
                        {{-- q:the select not adding movie into index
                            a: because the name of the input is movie_id not movie
                            --}}
                    </div>


                    <div class="flex justify-center">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/rooms/edit.blade.php
{{-- edit room table inspire from create --}}
@extends('welcome')
@section('content')

    <div class="m-5 flex justify-center">
        <div class="card w-96 bg-base-100 shadow-xl" data-theme='light'>
            <div class="card-body items-center text-center">
                <h2 class="card-title
            ">
                    Edit Room
                </h2>
                <form action="{{ route('room.update', $room->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text
                        ">Room Number</span>
                        </label>
                        <input type="text" name="no_room" placeholder="Room Number" class="input input-bordered"
                            value="{{ $room->no_room }}">
                    </div>
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text

">Number of Chairs</span>

                        </label>
                        <input type="text" name="no_chairs" placeholder="Number of Chairs" class="input input-bordered"
                            value="{{ $room->no_chairs }}">
                    </div>
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text ">Movie</span>
                        </label>
                        <select value="{{ $room->movies->id }}"  name="movie" class="select select-bordered w-full max-w-xs">
                            <option value="">Select Movie</option>
                            @foreach ($movies as $movie)
                                <option value="{{ $movie->id }}">{{ $movie->title }}</option>
                            @endforeach
                        </select>


                    </div>
                    <div class="flex justify-center">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/rooms/index.blade.php
{{-- index of room --}}
@extends('welcome')
@section('content')
<div class="m-5 flex justify-end" >
    <a class="btn btn-success" href="{{ route('room.create') }}">Add</a>
</div>
<div class="m-5" >
    <div class="overflow-x-auto" >
        <table class="table table-zebra w-full rounded-lg" data-theme="light">
          <!-- head -->
          <thead>
            <tr>
              <th>Number of Room</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($rooms as $item)
                <tr>
                    <td>{{ $item->no_room }}</td>
                    <td>
                        <form action="{{ route('room.destroy',$item->id) }}" method="post">
                            @csrf
                            @method('DELETE')

                            <a href="{{ route('room.show',$item->id) }}" class="btn btn-primary">Show</a>
                            <a href="{{ route('room.edit',$item->id) }}" class="btn btn-warning">Edit</a>
                            <button class="btn btn-error" onClick="return confirm('Are you sure you want to do this?')">Delete</button>
                        </form>
                    </td>
                </tr>

            @endforeach
          </tbody>
        </table>
      </div>
</div>
@endsection

resources/views/rooms/show.blade.php
@extends('welcome')
@section('content')
<div class="m-5 flex justify-center">
    <div class="card w-96 bg-base-100 shadow-xl" data-theme='light'>
        <div class="card-body items-center text-center">
          <h2 class="card-title">
            The Room : {{ $room->no_room }} Have {{ $room->no_chairs }}
          </h2>
          <p>This movie is Playing {{ $room->movies->title }} </p>
          <a href="{{ route('movie.show',$room->movies->id) }}" class="btn btn-success">Go to the movie</a>
          </div>
        </div>
      </div>


</div>
@endsection